### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by MrFuNK1** [Cselt/rf2-better-ui#8]
The installer is not working; it cannot locate the 7za.exe.

This might be an isolated issue in some scenarios: I was running the installer under Linux using Wine, so there could be some issue with it creating temporary files etc. that are required for the installation. However, I saw others reporting the same issue in the forum.

**Comment by Cselt** [comment]
Hi @MrFuNK1,

that's probably because the installer tries to find the rFactor 2 installer location in the registry, and if it's not found, then you'll see that error.

In the latest [2.3.3](https://github.com/Cselt/rf2-better-ui/releases/tag/v2.3.2) release I fixed that, and added a prompt to ask for the location if it's not found in the registry.

Please give it a try and let me know.

**Comment by MrFuNK1** [comment]
That will be the case - WINE does not know the location (system default WINE prefix used here and not the Proton/WINE prefix)
Will test later and report!

**Comment by MrFuNK1** [comment]
OK, installer does now work with WINE too thanks to the manual folder selection. Thanks!
